---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Deploy Nginx site config
  ansible.builtin.template:
    src: epicbook.conf.j2
    dest: /etc/nginx/sites-available/epicbook
  notify: restart nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook
    state: link
  notify: restart nginx

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
